### ISSUE TITLE
Failure to parse the icon name and label

### ISSUE THREAD

**Issue by mampcs** [caoqianli/apk-parser#42]
The apk meta parser fails to parse the icon name and label for the attached apk file, although it seems to be present correctly in the application line.
[example.zip](https://github.com/caoqianli/apk-parser/files/399348/example.zip)

**Comment by mampcs** [comment]
I'm using version 2.1.4

**Comment by caoqianli** [comment]
fixed in https://github.com/caoqianli/apk-parser/commit/3782656d1a1619648e45015f07e89ee069fd89b9

**Comment by mampcs** [comment]
Verified that the fix works. Thanks for the quick response.

**Comment by mampcs** [comment]
I found that the icon parsing issue is still there for the following attached apk.
Version 2.1.1 works fine for this apk.
Version 2.1.2 results in the following exception: java.lang.NumberFormatException: For input string: "0x20000"
Version 2.1.3 onwards
[missing.icon.name.zip](https://github.com/caoqianli/apk-parser/files/417286/missing.icon.name.zip)
 results in an empty icon name.

**Comment by mampcs** [comment]
Going to close this issue and open a new one instead.
